<a href="https://colab.research.google.com/github/Vangolds/DPDM/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #มอง data เป็น arrey นั่นก็คือเมทริกซ์

In [17]:
A = np.array([[1,2,3],[4,5,6]])
A #นับแถวที่ 0,1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
A.dot(A.T)

array([[14, 32],
       [32, 77]])

## Array slicing
คล้าย list slicing แต่มีสองมิติ

In [14]:
A[0,1] #ค่าที่อยู่ที่แถวที่1หลักที่2

2

In [15]:
A[:,:2] #เรียกค่าตั้งต้นกับค่ารองสุดท้าย ถ้าไม่ใส่เลขคือเอาทุกแถว [ทุกหลักมหลักที่ 0 ไปถึง 2]

array([[1, 2],
       [4, 5]])

In [16]:
A[1,1:]

array([5, 6])

## Distance matrix (Manhattan)

In [19]:
D = np.array([[1,2],[3,5],[2,0],[4,5]])
D

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [20]:
def Manhattan_dist(dp1,dp2):
    distX = abs(dp1[0-dp2[0]])
    distY = abs(dp1[1-dp2[1]])
    return distX + distY

In [30]:
dist_mat_man = np.zeros((4,4)) #สร้าง array เปล่าสองอัน
dist_mat_man

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(4):
    for j in range(4):
        dist_mat_man[i,j] = Manhattan_dist(D[i,:],D[j,:])

dist_mat_man

In [23]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#HW7