<a href="https://colab.research.google.com/github/Vangolds/DPDM/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #มอง data เป็น arrey นั่นก็คือเมทริกซ์

In [2]:
A = np.array([[1,2,3],[4,5,6]])
A #นับแถวที่ 0,1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
A.dot(A.T)

array([[14, 32],
       [32, 77]])

## Array slicing
คล้าย list slicing แต่มีสองมิติ

In [5]:
A[0,1] #ค่าที่อยู่ที่แถวที่1หลักที่2

2

In [6]:
A[:,:2] #เรียกค่าตั้งต้นกับค่ารองสุดท้าย ถ้าไม่ใส่เลขคือเอาทุกแถว [ทุกหลักมหลักที่ 0 ไปถึง 2]

array([[1, 2],
       [4, 5]])

In [7]:
A[1,1:]

array([5, 6])

## Distance matrix (Manhattan)

In [8]:
data1 = np.array([[1,2],[3,5],[2,0],[4,5]])
data1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [9]:
def Manhattan_dist(dp1,dp2):
    distX = abs(dp1[0]-dp2[0])
    distY = abs(dp1[1]-dp2[1])
    return distX + distY

In [10]:
dist_mat_man = np.zeros((4,4))
dist_mat_man

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
for i in range(4):
    for j in range(4):
        dist_mat_man[i,j] = Manhattan_dist(data1[i,:],data1[j,:]) 

dist_mat_man 

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

#HW6

In [12]:
data1 = np.array([[1,2],[3,5],[2,0],[4,5]])
data1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [13]:
import math

In [14]:
 def Euclidean_dist(dp1,dp2):
    distX = abs(dp1[0]-dp2[0])
    distY = abs(dp1[1]-dp2[1])
    return math.sqrt(math.pow(distX,2) + math.pow(distY,2))

In [15]:
dist_eu_cli = np.zeros((4,4))
dist_eu_cli

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
for i in range(4):
    for j in range(4):
        dist_eu_cli[i,j] = Euclidean_dist(data1[i,:],data1[j,:]) 

dist_eu_cli

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

#Distance of nominal or catagorical features
(extra) Phython data structure (Dictionary)

In [17]:
d_A = {'a':1,2:3,3:5,'cat':6}
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [18]:
d_A['cat'] #index cat

6

In [19]:
d_A['dag'] = [1,2,3,4,5]


In [20]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dag': [1, 2, 3, 4, 5]}

In [21]:
del d_A[2]

In [22]:
d_A

{3: 5, 'a': 1, 'cat': 6, 'dag': [1, 2, 3, 4, 5]}

In [23]:
import pandas as pd


In [25]:
data_dict = {'color':['red','red','green'],
             'status':['single','married','single']}
data_dict

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

In [26]:
data_pd = pd.DataFrame.from_dict(data_dict)

In [27]:
data_pd

color   status
0    red   single
1    red  married
2  green   single

#Categoriccal feature distance method #1

In [28]:
list(data_pd.iloc[1,:]) #แถวที่1 ทุกหลัก

['red', 'married']

In [37]:
def meth1_dist(data1,data2):
  N = 0
  print(f'data is {data1} and data2 is {data2}')
  for i in range(len(data1)):
    if data1[i] != data2[i]:
      print(f'feature{i} of data1 is {data1[i]}, feature{i} of data2 is {data2[i]}')
      N = N + 1
      print(f' {data1[i]} is not equal {data2[i]} : update ({N})')
    else:
      print(f' {data1[i]} is equal {data2[i]} : update ({N})')
  return N/len(data1)


In [38]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

data is ['red', 'single'] and data2 is ['red', 'married']
 red is equal red : update (0)
feature1 of data1 is single, feature1 of data2 is married
 single is not equal married : update (1)


0.5

#HW7 calculate distance matrix of data_pd using meth1_dist()

In [39]:
dist_C = np.zeros((3,3))
dist_C

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
for i in range(3):
    for j in range(3):
        dist_C[i,j] = meth1_dist(list(data_pd.iloc[i,:]),list(data_pd.iloc[j,:]))

dist_C

data is ['red', 'single'] and data2 is ['red', 'single']
 red is equal red : update (0)
 single is equal single : update (0)
data is ['red', 'single'] and data2 is ['red', 'married']
 red is equal red : update (0)
feature1 of data1 is single, feature1 of data2 is married
 single is not equal married : update (1)
data is ['red', 'single'] and data2 is ['green', 'single']
feature0 of data1 is red, feature0 of data2 is green
 red is not equal green : update (1)
 single is equal single : update (1)
data is ['red', 'married'] and data2 is ['red', 'single']
 red is equal red : update (0)
feature1 of data1 is married, feature1 of data2 is single
 married is not equal single : update (1)
data is ['red', 'married'] and data2 is ['red', 'married']
 red is equal red : update (0)
 married is equal married : update (0)
data is ['red', 'married'] and data2 is ['green', 'single']
feature0 of data1 is red, feature0 of data2 is green
 red is not equal green : update (1)
feature1 of data1 is married, fe

array([[0. , 0.5, 0.5],
       [0.5, 0. , 1. ],
       [0.5, 1. , 0. ]])

#Categorical feature distance method#2

In [50]:
data_dict2 = {'color':['red','red','green','blue'],
             'status':['single','married','single','divorced']}
data_pd2 = pd.DataFrame.from_dict(data_dict2)
data_pd2

color    status
0    red    single
1    red   married
2  green    single
3   blue  divorced

In [52]:
data_pd_binary = pd.get_dummies(data_pd2)
data_pd_binary = data_pd_binary.iloc[:3,:]

data_pd_binary

color_blue  color_green  ...  status_married  status_single
0           0            0  ...               0              1
1           0            0  ...               1              0
2           0            1  ...               0              1

[3 rows x 6 columns]

In [57]:
def binary_sym_dist(data1,data2):
  r=0
  s=0
  t=0
  q=0
  #print(f'data is {data1} and data2 is {data2}')
  for i in range(len(data1)):
    if data1[i] != data2[i]:
      if data1[i] == 0:
        s = s + 1
      else:
        r = r + 1
    else:
      if data1[i] == 0:
        t =t + 1
      else:
        q = q +  1
  return (r+s)/(r+s+q+t)

In [60]:
binary_sym_dist(list(data_pd_binary.iloc[0,:]),list(data_pd_binary.iloc[1,:]))

0.3333333333333333

#HW8 calculate distance matrix of data_pd_binary using binary_sym_dist

In [62]:
dist_data_pd2 = np.zeros((3,3)) 
dist_data_pd2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
for i in range(3):
  for j in range(3):
    dist_data_pd2[i,j] = binary_sym_dist(list(data_pd_binary.iloc[i,:]),list(data_pd_binary.iloc[j,:]))
dist_data_pd2


array([[0.        , 0.33333333, 0.33333333],
       [0.33333333, 0.        , 0.66666667],
       [0.33333333, 0.66666667, 0.        ]])