<a href="https://colab.research.google.com/github/Vangolds/DPDM/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np #มอง data เป็น arrey นั่นก็คือเมทริกซ์

In [20]:
A = np.array([[1,2,3],[4,5,6]])
A #นับแถวที่ 0,1

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
A.dot(A.T)

array([[14, 32],
       [32, 77]])

## Array slicing
คล้าย list slicing แต่มีสองมิติ

In [23]:
A[0,1] #ค่าที่อยู่ที่แถวที่1หลักที่2

2

In [24]:
A[:,:2] #เรียกค่าตั้งต้นกับค่ารองสุดท้าย ถ้าไม่ใส่เลขคือเอาทุกแถว [ทุกหลักมหลักที่ 0 ไปถึง 2]

array([[1, 2],
       [4, 5]])

In [25]:
A[1,1:]

array([5, 6])

## Distance matrix (Manhattan)

In [31]:
data1 = np.array([[1,2],[3,5],[2,0],[4,5]])
data1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [32]:
def Manhattan_dist(dp1,dp2):
    distX = abs(dp1[0]-dp2[0])
    distY = abs(dp1[1]-dp2[1])
    return distX + distY

In [33]:
dist_mat_man = np.zeros((4,4))
dist_mat_man

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
for i in range(4):
    for j in range(4):
        dist_mat_man[i,j] = Manhattan_dist(data1[i,:],data1[j,:]) 

dist_mat_man 

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

#HW6

In [ ]:
data1 = np.array([[1,2],[3,5],[2,0],[4,5]])
data1

In [45]:
import math

In [43]:
 def Euclidean_dist(dp1,dp2):
    distX = abs(dp1[0]-dp2[0])
    distY = abs(dp1[1]-dp2[1])
    return math.sqrt(math.pow(distX,2) + math.pow(distY,2))

In [39]:
dist_eu_cli = np.zeros((4,4))
dist_eu_cli

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
for i in range(4):
    for j in range(4):
        dist_eu_cli[i,j] = Euclidean_dist(data1[i,:],data1[j,:]) 

dist_eu_cli

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])